 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package optimasipakansapi;

import java.text.DecimalFormat;
import java.util.List;
import java.util.ArrayList;
//import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author noortopik
 */
public class halamanNutrisi extends javax.swing.JFrame {

    /**
     * Creates new form halamanNutrisi
     */
    DecimalFormat df = new DecimalFormat(".##");
    PakanSapi ps = new PakanSapi();
    KebutuhanNutrisi KN = new KebutuhanNutrisi();
    private DefaultTableModel model;
    List<KebutuhanNutrisi> listNutrisi = new ArrayList<>();
    List<KebutuhanNutrisi> pbbh = new ArrayList<>();
    int x = 0;

    public double BK;
    public double PK;
    public double TDN;
    public double Ca;
    public double P;
    int BB;
    int kategori;
    String Pakan1;
    String Pakan2;
    String Pakan3;
    String Pakan4;
    String Jenis_Sapi;
    double pbb;
    private PakanSapi PakanSapi;

    public halamanNutrisi() {
        initComponents();

    }

    private void buatTable() {
        model = new DefaultTableModel();
        model.addColumn("Nama Pakan");
        model.addColumn("Harga(/Kg)");
        model.addColumn("BK(%)");
        model.addColumn("PK(%)");
        model.addColumn("TDN(%)");
        model.addColumn("Ca(%)");
        model.addColumn("P(%)");
        tblNutrisi.setModel(model);
    }

    private void tampilTable() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        listNutrisi.clear();
        listNutrisi = ps.tampil(Pakan1, Pakan2, Pakan3, Pakan4);
        for (x = 0; x < listNutrisi.size(); x++) {
            Object[] data = new Object[7];
            data[0] = listNutrisi.get(x).getBahan_pakan();
            data[1] = listNutrisi.get(x).getHarga();
            data[2] = listNutrisi.get(x).getBK();
            data[3] = listNutrisi.get(x).getPK();
            data[4] = listNutrisi.get(x).getTDN();
            data[5] = listNutrisi.get(x).getCa();
            data[6] = listNutrisi.get(x).getP();
            model.addRow(data);
        }
    }

    private void clearTable() {
        DefaultTableModel model1 = (DefaultTableModel) tblNutrisi.getModel();
        while (model1.getRowCount() > 0) {
            for (int i = 0; i < model1.getRowCount(); i++) {
                model1.removeRow(i);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel17 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        combopbb = new javax.swing.JComboBox();
        txtberatbadan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBK = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPK = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTDN = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtCa = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtP = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        combopakanke1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        combopakanke2 = new javax.swing.JComboBox();
        combopakanke3 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblNutrisi = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        combojenissapi = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtPakanMin = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txthijauan = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtkonsentrat = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        combopakanke4 = new javax.swing.JComboBox();
        btnpbb = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnhitungnutrisi = new javax.swing.JButton();
        btnoptimasi = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jLabel17.setText("jLabel17");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Berat Badan               :");

        jLabel2.setText("Target Berat Badan  :");

        combopbb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combopbbMouseClicked(evt);
            }
        });
        combopbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combopbbActionPerformed(evt);
            }
        });

        txtberatbadan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtberatbadanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtberatbadanMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtberatbadanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtberatbadanMouseReleased(evt);
            }
        });
        txtberatbadan.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtberatbadanInputMethodTextChanged(evt);
            }
        });
        txtberatbadan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtberatbadanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Kebutuhan Nutrisi yang Harus Di Penuhi");

        jLabel4.setText("Berat Kering");

        jLabel5.setText("Protein Kering");

        jLabel6.setText("Total Digestible Nutrien");

        txtBK.setEditable(false);
        jScrollPane1.setViewportView(txtBK);

        txtPK.setEditable(false);
        jScrollPane3.setViewportView(txtPK);

        txtTDN.setEditable(false);
        jScrollPane2.setViewportView(txtTDN);

        jLabel7.setText("Calsium");

        txtCa.setEditable(false);
        jScrollPane4.setViewportView(txtCa);

        jLabel8.setText("Fosfor");

        txtP.setEditable(false);
        jScrollPane5.setViewportView(txtP);

        jLabel9.setText("Kg");

        jLabel10.setText("Kg");

        jLabel11.setText("Pakan Hijauan ke-1:");

        combopakanke1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Silahkan Pilih...", "Jerami (J) Padi Segar", "J. Padi Kering", "J. Jagung Bag.Atas Segar", "Rumput Gajah", "Rumput Benggala", "Rumput Ilalang", "Rendeng Segar", "Rendeng Kering", "Lamtoro Segar", "Lamtoro Kering", "Daun Ketela Pohon Segar", "Daun Gliricida Segar" }));
        combopakanke1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combopakanke1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Pakan Konsentrat ke-1:");

        jLabel13.setText("Pakan Konsentrat ke-2  :");

        combopakanke2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Silahkan Pilih...", "Dedak Halus Padi", "Dedak Jagung", "Dedak Gandum", "Jagung Kuning", "Onggok", "Tetes", "Bungkil Kedelai", "Bungkil Kapas", "Bungkil Kelapa Sawit", "Bungkil Kelapa", "Bungkil Kacang", "Bungkil Kapok", "Geplek", "Cantel" }));
        combopakanke2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combopakanke2ActionPerformed(evt);
            }
        });

        combopakanke3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Silahkan Pilih...", "Dedak Halus Padi", "Dedak Jagung", "Dedak Gandum", "Jagung Kuning", "Onggok", "Tetes", "Bungkil Kedelai", "Bungkil Kapas", "Bungkil Kelapa Sawit", "Bungkil Kelapa", "Bungkil Kacang", "Bungkil Kapok", "Geplek", "Cantel" }));
        combopakanke3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combopakanke3ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel14.setText("Optimasi Pakan Untuk Penggemukan Sapi Potong");

        jLabel15.setText("gram");

        jLabel16.setText("Kg");

        jLabel18.setText("Kg");

        jLabel19.setText("gram");

        jLabel20.setText("gram");

        tblNutrisi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Pakan", "Harga", "BK", "PK", "TDN", "Ca", "P"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNutrisi.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(tblNutrisi);
        if (tblNutrisi.getColumnModel().getColumnCount() > 0) {
            tblNutrisi.getColumnModel().getColumn(0).setResizable(false);
            tblNutrisi.getColumnModel().getColumn(1).setResizable(false);
            tblNutrisi.getColumnModel().getColumn(2).setResizable(false);
            tblNutrisi.getColumnModel().getColumn(3).setResizable(false);
            tblNutrisi.getColumnModel().getColumn(4).setResizable(false);
            tblNutrisi.getColumnModel().getColumn(5).setResizable(false);
            tblNutrisi.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setText("Daftar Nutrisi Pakan Yang Telah Dipilih");

        combojenissapi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sapi Jantan", "Sapi Dara", "Sapi Menyusui" }));
        combojenissapi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combojenissapiActionPerformed(evt);
            }
        });

        jLabel22.setText(" Jenis Sapi                  :");

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel23.setText("Data Keterangan Sapi");

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setText("Daftar Kebutuhan Pakan");

        txtPakanMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPakanMinActionPerformed(evt);
            }
        });

        jLabel25.setText("Berat Pakan Minimum");

        jLabel26.setText("Kg");

        txthijauan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthijauanActionPerformed(evt);
            }
        });

        jLabel27.setText("Minimum Hijauan");

        txtkonsentrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkonsentratActionPerformed(evt);
            }
        });

        jLabel28.setText("Minimum Konsentrat");

        jLabel29.setText("Kg");

        jLabel30.setText("Kg");

        jLabel31.setText("Pakan Konsentrat ke-3  :");

        combopakanke4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Silahkan Pilih...", "Dedak Halus Padi", "Dedak Jagung", "Dedak Gandum", "Jagung Kuning", "Onggok", "Tetes", "Bungkil Kedelai", "Bungkil Kapas", "Bungkil Kelapa Sawit", "Bungkil Kelapa", "Bungkil Kacang", "Bungkil Kapok", "Geplek", "Cantel" }));
        combopakanke4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combopakanke4ActionPerformed(evt);
            }
        });

        btnpbb.setText("Lihat Penambahan Berat Badan");
        btnpbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpbbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(txtberatbadan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9))
                                    .addComponent(combojenissapi, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnpbb)))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(combopakanke2, 0, 182, Short.MAX_VALUE)
                                    .addComponent(combopakanke1, 0, 182, Short.MAX_VALUE)
                                    .addComponent(combopakanke3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(combopakanke4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(16, 16, 16)
                                .addComponent(combopbb, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel24))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtkonsentrat, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel30))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane1Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtPakanMin, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(25, 25, 25)))
                        .addGap(49, 49, 49)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txthijauan, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel29))
                    .addComponent(jScrollPane6)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane1Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combojenissapi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9)
                            .addComponent(txtberatbadan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnpbb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(combopbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txthijauan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel27)
                                .addComponent(jLabel29)))
                        .addGap(15, 15, 15)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                                .addComponent(jLabel28)
                                .addComponent(txtkonsentrat)
                                .addComponent(jLabel30)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPakanMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel25)
                                .addComponent(jLabel26)))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(combopakanke1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(combopakanke2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combopakanke3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combopakanke4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31)))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(combopbb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtberatbadan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(combopakanke1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(combopakanke2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(combopakanke3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(combojenissapi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtPakanMin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txthijauan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtkonsentrat, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel29, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel31, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(combopakanke4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnpbb, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btnhitungnutrisi.setText("Hitung Nutrisi");
        btnhitungnutrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungnutrisiActionPerformed(evt);
            }
        });

        btnoptimasi.setText("Optimasikan");
        btnoptimasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoptimasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnhitungnutrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270)
                .addComponent(btnoptimasi, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnreset)
                    .addComponent(btnhitungnutrisi)
                    .addComponent(btnoptimasi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnoptimasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoptimasiActionPerformed
        // TODO add your handling code here:
        String pkn1 = Pakan1;
        String pkn2 = Pakan2;
        String pkn3 = Pakan3;
        String pkn4 = Pakan4;
        String jenis_sapi = Jenis_Sapi;
        HalamanAlgen ha = new HalamanAlgen();
        ha.buatTable(pkn1, pkn2, pkn3, pkn4, ps.getBeratBadan(), ps.getPbb(), jenis_sapi);
//        this.dispose();
        ha.setVisible(true);
    }//GEN-LAST:event_btnoptimasiActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        txtberatbadan.setText("");
        txtBK.setText("");
        txtPK.setText("");
        txtTDN.setText("");
        txtCa.setText("");
        txtP.setText("");
        clearTable();
    }//GEN-LAST:event_btnresetActionPerformed

    private void combopakanke3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combopakanke3ActionPerformed
        // TODO add your handling code here:
        Pakan3 = (String) combopakanke3.getSelectedItem();
        //        int kategori_pakan3 = kategori(Pakan3);
    }//GEN-LAST:event_combopakanke3ActionPerformed

    private void combopakanke2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combopakanke2ActionPerformed
        // TODO add your handling code here:
        Pakan2 = (String) combopakanke2.getSelectedItem();
        //        int kategori_pakan2 = kategori(Pakan2);
    }//GEN-LAST:event_combopakanke2ActionPerformed

    private void combopakanke1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combopakanke1ActionPerformed
        // TODO add your handling code here:
        Pakan1 = (String) combopakanke1.getSelectedItem();
    }//GEN-LAST:event_combopakanke1ActionPerformed

    private void btnhitungnutrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungnutrisiActionPerformed
        // TODO add your handling code here:
        pbb = (Double) combopbb.getSelectedItem();
        ps.setPbb(pbb);
        ps.setBeratBadan(BB);

        listNutrisi.clear();
        listNutrisi = ps.tampilKebutuhan(BB, pbb, Jenis_Sapi);
        txtBK.setText(String.valueOf(listNutrisi.get(0).getBK()));
        txtPK.setText(String.valueOf(listNutrisi.get(0).getPK()));
        txtTDN.setText(String.valueOf(listNutrisi.get(0).getTDN()));
        txtCa.setText(String.valueOf(listNutrisi.get(0).getCa()));
        txtP.setText(String.valueOf(listNutrisi.get(0).getP()));
        double pakan_min = Double.valueOf(df.format(BB * (listNutrisi.get(0).getKemampuan_konsumsi()) / 100));
        if (pbb != 0) {
            txtPakanMin.setText(String.valueOf(pakan_min));
        } else {
            txtPakanMin.setText(String.valueOf(listNutrisi.get(0).getBK()));
        }
        txthijauan.setText(String.valueOf(Double.valueOf(df.format(pakan_min * 0.6))));
        txtkonsentrat.setText(String.valueOf(Double.valueOf(df.format(pakan_min * 0.4))));

        buatTable();
        tampilTable();
    }//GEN-LAST:event_btnhitungnutrisiActionPerformed

    private void txtberatbadanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtberatbadanActionPerformed
        // TODO add your handling code here:
        BB = Integer.parseInt(txtberatbadan.getText());
    }//GEN-LAST:event_txtberatbadanActionPerformed

    private void combopbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combopbbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combopbbActionPerformed

    private void combojenissapiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combojenissapiActionPerformed
        // TODO add your handling code here:
        Jenis_Sapi = (String) combojenissapi.getSelectedItem();
    }//GEN-LAST:event_combojenissapiActionPerformed

    private void txtPakanMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPakanMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPakanMinActionPerformed

    private void txthijauanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthijauanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthijauanActionPerformed

    private void txtkonsentratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkonsentratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkonsentratActionPerformed

    private void combopakanke4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combopakanke4ActionPerformed
        // TODO add your handling code here:
        Pakan4 = (String) combopakanke4.getSelectedItem();
    }//GEN-LAST:event_combopakanke4ActionPerformed

    private void txtberatbadanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtberatbadanMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtberatbadanMouseEntered

    private void txtberatbadanInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtberatbadanInputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_txtberatbadanInputMethodTextChanged

    private void txtberatbadanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtberatbadanMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtberatbadanMousePressed

    private void txtberatbadanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtberatbadanMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtberatbadanMouseReleased

    private void txtberatbadanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtberatbadanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtberatbadanMouseClicked

    private void combopbbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combopbbMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_combopbbMouseClicked

    private void btnpbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpbbActionPerformed
        // TODO add your handling code here:
        combopbb.removeAllItems();
        pbbh.clear();
        pbbh = ps.daftarpbbh(BB, Jenis_Sapi);
        for (x = 0; x < pbbh.size(); x++) {
            Object[] data = new Object[1];
            data[0] = pbbh.get(x).getPbbh();
            combopbb.addItem(data[0]);
        }
    }//GEN-LAST:event_btnpbbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halamanNutrisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halamanNutrisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halamanNutrisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halamanNutrisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new halamanNutrisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhitungnutrisi;
    private javax.swing.JButton btnoptimasi;
    private javax.swing.JButton btnpbb;
    private javax.swing.JButton btnreset;
    private javax.swing.JComboBox combojenissapi;
    private javax.swing.JComboBox combopakanke1;
    private javax.swing.JComboBox combopakanke2;
    private javax.swing.JComboBox combopakanke3;
    private javax.swing.JComboBox combopakanke4;
    private javax.swing.JComboBox combopbb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tblNutrisi;
    private javax.swing.JTextPane txtBK;
    private javax.swing.JTextPane txtCa;
    private javax.swing.JTextPane txtP;
    private javax.swing.JTextPane txtPK;
    private javax.swing.JTextField txtPakanMin;
    private javax.swing.JTextPane txtTDN;
    private javax.swing.JTextField txtberatbadan;
    private javax.swing.JTextField txthijauan;
    private javax.swing.JTextField txtkonsentrat;
    // End of variables declaration//GEN-END:variables
}
